package net.digihippo.aoc;

public class ElevenTest extends TestTemplate<Long, Long> {

    private static final String EXAMPLE_INPUT = """
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
            """;

    public ElevenTest() {
        super(new Eleven(), EXAMPLE_INPUT, 374L, 82000210L, "eleven.txt");
    }
}
